# Making rasters for shiny_indicators app 
# ----- MOST RECENT UPDATE, PULLED DATA FROM SERVER 10-11-2024, from OCT 3---#
#library(raster)
library(RColorBrewer)
library(ncdf4)
library(wesanderson)
library(terra)
library(dplyr)
setwd(here::here('app'))
source(here::here('functions/func_convertdateNcdf2R.R'))
# Color Palette
# Continuous palette for displaying smoother images
cols = rev(brewer.pal(11,'RdYlBu'))
pal <- colorRampPalette(cols)(30)

## Getting files from ACSPO and GLOBCOLOR - generated by Kim
# path = here::here('nc_files/ww')
path = here::here('nc_files/')
# files <- list.files(path = path, pattern = glob2rx('WW_2021*.nc'),
#                     full.names = TRUE)
files <- list.files(path = path, pattern = glob2rx('WW_*.nc'),
                    full.names = TRUE)

## -- Saving -- ## 
i= 13 # 8
## SST STAT
# Stat
nc <- nc_open(files[i])  # Open files # 3 2022:stats, 4 2022:anom 
# 9 -2023 sst stats, 10-2023 chl stats, 11-2023 chl anom
# 12-2023 sst anom, 13- 2024 sst stats, 14- 2024chl stats, 15-2024 chl anom, 16-2024 sst anom
lat <- ncvar_get(nc, 'latitude')
lon <- ncvar_get(nc, 'longitude')
sst <- ncvar_get(nc, attributes(nc$var)$names[5]) # "SST_MEAN"
t <- ncvar_get(nc, 'time')  # Extract time 
tunits <- ncatt_get(nc,'time','units') # identify units for the conversion
splitt <- strsplit(tunits$value, " ") # parse time units for conversion
# convert dates!
ptime <- convertDateNcdf2R(t, unlist(splitt)[1], 
                           origin =  as.POSIXct(unlist(splitt)[3], tz = "UTC"), 
                           time.format = "%Y-%m-%d")
ptime <- lubridate::ymd(ptime)
r = terra::flip(t(terra::rast(sst)), direction='vertical')
# set the layer names to the dates you extracted earlier
names(r) <- ptime 
# save time component in spatraster object
terra::time(r) <- names(r) %>%  lubridate::ymd() %>% as.Date() 

ext(r) <- c(xmn = min(lon), xmx = max(lon), # set extent
            ymn = min(lat), ymx = max(lat))
crs(r)  <- 'epsg:4326' # set a projection, WGS 84 has EPSG code 4326

# Save your raster as a geotif: 
# (change the start/stop values based on the location of the date in your filename)
terra::writeRaster(r, filename = paste0('sst_', 
                                        substr(files[i],
                                               start = 81, stop = 84), '.tif'))

nc_close(nc)
rm(nc)
## SST ANOM
i = 16
nc <- nc_open(files[i])  # Open files
sst <- ncvar_get(nc, attributes(nc$var)$names[1]) # "SST_MEAN"

t <- ncvar_get(nc, 'time')  # Extract time 
tunits <- ncatt_get(nc,'time','units') # identify units for the conversion
splitt <- strsplit(tunits$value, " ") # parse time units for conversion
# convert dates!
ptime <- convertDateNcdf2R(t, unlist(splitt)[1], 
                           origin =  as.POSIXct(unlist(splitt)[3], tz = "UTC"), 
                           time.format = "%Y-%m-%d")
ptime <- lubridate::ymd(ptime)
r = terra::flip(t(terra::rast(sst)), direction='vertical')
# set the layer names to the dates you extracted earlier
names(r) <- ptime 
# save time component in spatraster object
terra::time(r) <- names(r) %>%  lubridate::ymd() %>% as.Date() 

ext(r) <- c(xmn = min(lon), xmx = max(lon), # set extent
            ymn = min(lat), ymx = max(lat))
crs(r)  <- 'epsg:4326' # set a projection, WGS 84 has EPSG code 4326
nc_close(nc)
rm(nc)
terra::writeRaster(r, filename = paste0('sst_anom_', 
                                        substr(files[i],
                                               start = 81, stop = 84), '.tif'))

## CHL 
i = 14
nc <- nc_open(files[i])  # Open files
lat <- ncvar_get(nc, 'latitude')
lon <- ncvar_get(nc, 'longitude')
chl <- ncvar_get(nc, attributes(nc$var)$names[4])
t <- ncvar_get(nc, 'time')  # Extract time 
tunits <- ncatt_get(nc,'time','units') # identify units for the conversion
splitt <- strsplit(tunits$value, " ") # parse time units for conversion
# convert dates!
ptime <- convertDateNcdf2R(t, unlist(splitt)[1], 
                           origin =  as.POSIXct(unlist(splitt)[3], tz = "UTC"), 
                           time.format = "%Y-%m-%d")
ptime <- lubridate::ymd(ptime)
r = terra::flip(t(terra::rast(chl)), direction='vertical')
# set the layer names to the dates you extracted earlier
names(r) <- ptime 
# save time component in spatraster object
terra::time(r) <- names(r) %>%  lubridate::ymd() %>% as.Date() 

ext(r) <- c(xmn = min(lon), xmx = max(lon), # set extent
            ymn = min(lat), ymx = max(lat))
crs(r)  <- 'epsg:4326' # set a projection, WGS 84 has EPSG code 4326
nc_close(nc)
rm(nc)
terra::writeRaster(r, filename = paste0('chl_', 
                                        substr(files[i],
                                               start = 81, stop = 84), '.tif'))



## CHL ANOM 
i=15
nc <- nc_open(files[i])  # Open files
lat <- ncvar_get(nc, 'latitude')
lon <- ncvar_get(nc, 'longitude')
chl <- ncvar_get(nc, attributes(nc$var)$names[1])
t <- ncvar_get(nc, 'time')  # Extract time 
tunits <- ncatt_get(nc,'time','units') # identify units for the conversion
splitt <- strsplit(tunits$value, " ") # parse time units for conversion
# convert dates!
ptime <- convertDateNcdf2R(t, unlist(splitt)[1], 
                           origin =  as.POSIXct(unlist(splitt)[3], tz = "UTC"), 
                           time.format = "%Y-%m-%d")
ptime <- lubridate::ymd(ptime)
r = terra::flip(t(terra::rast(chl)), direction='vertical')
# set the layer names to the dates you extracted earlier
names(r) <- ptime 
# save time component in spatraster object
terra::time(r) <- names(r) %>%  lubridate::ymd() %>% as.Date() 

ext(r) <- c(xmn = min(lon), xmx = max(lon), # set extent
            ymn = min(lat), ymx = max(lat))
crs(r)  <- 'epsg:4326' # set a projection, WGS 84 has EPSG code 4326
nc_close(nc)
rm(nc)
terra::writeRaster(r, filename = paste0('chl_anom_', 
                                        substr(files[i],
                                               start = 78, stop = 81), '.tif'))







